### ISSUE TITLE
Some null Error

### ISSUE THREAD

**Issue by Julienraptor01** [dlee13/hold-that-chunk#15]
i go from one crystal hollow lobby to one other in hypixel using the minecart in the menu and sometimes when it warp between servers this happen
the only way to get out of this is crashing the game
```
[00:40:39] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_2935()" because "this.field_3699" is null
	at net.minecraft.class_634.method_11107(class_634.java:742) ~[client-intermediary.jar:?]
	at xyz.holocons.mc.holdthatchunk.ChunkUnloader.onChunkLoad(ChunkUnloader.java:42) ~[holdthatchunk-2.0.0+1.19.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientChunkEvents.lambda$static$0(ClientChunkEvents.java:45) ~[fabric-lifecycle-events-v1-2.2.2+9244241690-8d030d6d247934ee.jar:?]
	at net.minecraft.class_631.handler$bcc000$onChunkLoad(class_631.java:1051) ~[client-intermediary.jar:?]
	at net.minecraft.class_631.method_16020(class_631.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38539(class_634.java:709) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11128(class_634.java:704) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
![image](https://user-images.githubusercontent.com/49841713/209413796-9537a9d3-8128-43cd-b16f-2905663f31f9.png)

**Comment by dlee13** [comment]
That was already fixed. Use Hold That Chunk v2.0.1.

**Comment by Julienraptor01** [comment]
Oh sorry idk why but when i looked for this mod 2.0.1 wasn't there when i filtered by version 1.19.2
